### ISSUE TITLE
bert_embedding_cub

### ISSUE THREAD

**Issue by lizhangweia** [dqshuai/MetaFormer#13]
作者您好，可以提供一下bert_embedding_cub这个文件吗？我在使用meta训练的时候报错了，非常感谢！

**Comment by dqshuai** [comment]
https://github.com/dqshuai/MetaFormer/issues/8#issuecomment-1082987046 可以看下这个issues里的链接。

**Comment by lizhangweia** [comment]
好的，感谢作者。

**Comment by moon-wh** [comment]
> 作者您好，可以提供一下bert_embedding_cub这个文件吗？我在使用meta训练的时候报错了，非常感谢！

你好，不好意思打扰了，请问你有这个文件了吗？作者分享的链接无效了

**Comment by lizhangweia** [comment]
> > 作者您好，可以提供一下bert_embedding_cub这个文件吗？我在使用meta训练的时候报错了，非常感谢！
> 
> 你好，不好意思打扰了，请问你有这个文件了吗？作者分享的链接无效了

不好意思，之前实验结果一直不好，就把这个项目删了，现在也就找不到这个文件了。

**Comment by moon-wh** [comment]
好的谢谢，麻烦您了
----- 原始邮件 -----
发件人：lizhangweia ***@***.***>
收件人：dqshuai/MetaFormer ***@***.***>
抄送人：moon-wh ***@***.***>,  Comment ***@***.***>
主题：Re: [dqshuai/MetaFormer] bert_embedding_cub (Issue #13)
日期：2023年01月20日 21点09分




作者您好，可以提供一下bert_embedding_cub这个文件吗？我在使用meta训练的时候报错了，非常感谢！

你好，不好意思打扰了，请问你有这个文件了吗？作者分享的链接无效了

不好意思，之前实验结果一直不好，就把这个项目删了，现在也就找不到这个文件了。

&mdash;
