### ISSUE TITLE
Some errata found on the code

### ISSUE THREAD

**Issue by seungwoos** [dqshuai/MetaFormer#21]
Hi, 
Thanks for sharing wonderful work :) 

While running the code, I found some minor errata building the data augmentation module.

https://github.com/dqshuai/MetaFormer/blob/669bf18c35fdb51e35b0a79fa86224a18cd38ac5/data/build.py#L16

I guess this line should fixed with
`from timm.data.transforms import str_to_pil_interp` 
since there is no `_pil_interp` in `timm.data.transforms`. https://github.com/rwightman/pytorch-image-models/blob/master/timm/data/transforms.py

If there is something I missed, pleased let me know :)

**Comment by dqshuai** [comment]
@seungwoos Hi,
I think it is the difference of version, and i used timm==0.4.5. https://github.com/rwightman/pytorch-image-models/blob/v0.4.5/timm/data/transforms.py#L43

**Comment by seungwoos** [comment]
Thank you so much for your reply :)

I used the latest version of timm so that this happened. 
Thank you.
