### ISSUE TITLE
I have a question about "linear embbeding" and "non-linear embbeding".

### ISSUE THREAD

**Issue by manakahasegawa** [dqshuai/MetaFormer#5]
Thanks for all your great work!

I have two questions about the paper.

1. Is figure 2 on page 4 of the paper and figure 1 on page 10 of the paper referring to the same architecture?

2. The term "non-linear embbedding" and "linear embbedding" are used to describe embedding meta-information, but if the figures refer to the same architecture, what is the intention behind the different designations?
Neural networks are iterations of processes that perform linear transformations and activation functions that perform nonlinear transformations. Is it correct to say that you used "non-linear embbedding" because you are using an activation function relu that performs a non-linear transformation?

**Comment by dqshuai** [comment]
hi, it's my bad. All description should be "non-linear embbedding". As you said, we used relu to performs a non-linear transfromation.
