### ISSUE TITLE
How to generate bert_embedding_cub for cub-200?

### ISSUE THREAD

**Issue by BakingBrains** [dqshuai/MetaFormer#7]
`FileNotFoundError: [Errno 2] No such file or directory: 'D:/dataset/CUB_200_2011\\bert_embedding_cub\\001.Black_footed_Albatross/Black_Footed_Albatross_0046_18.pickle'`

**Comment by dqshuai** [comment]
We used the  to [https://github.com/huggingface/transformers](url) generate bert embedding. For example,
`from transformers import AutoTokenizer, AutoModel  `
`tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")  `
`model = AutoModel.from_pretrained("bert-base-uncased")  `.

**Comment by BakingBrains** [comment]
@dqshuai Thanks a lot, can you please tell on which meta data (in cub-200) should we generate embeddings.pkl file?
